FROM smsntia/uhd_b2xx_py3

RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive \
                   apt-get install -qy --no-install-recommends \
                   libboost-date-time1.65.1 libboost-filesystem1.65.1 \
                   libboost-python1.65.1 libboost-regex1.65.1 \
                   libboost-serialization1.65.1 libboost-system1.65.1 \
                   libboost-thread1.65.1 libusb-1.0-0 libpython3.6 \
                   libboost-program-options1.65.1 \
                   git python3-setuptools python3-pip python3-numpy \
		   swig gcc python3-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED 1
RUN mkdir -p /src
WORKDIR /src
COPY ./ /src

ARG DOCKER_GIT_CREDENTIALS
RUN python3 -m pip install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements-dev.txt

ENTRYPOINT ["pytest"]
