FROM ubuntu:20.04


RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -qy --no-install-recommends \
    git python3 python3-pip \
    python3-dev python3-uhd && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED 1
RUN mkdir -p /src
WORKDIR /src
COPY ./ /src

ARG DOCKER_GIT_CREDENTIALS
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --no-cache-dir .[test]

ENTRYPOINT ["pytest"]
