FROM ubuntu:22.04

RUN apt-get update -q && apt-get upgrade -yq

RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive \
                   apt-get install -qy --no-install-recommends \
                   python3 python3-pip \
                   python3-dev python3-uhd uhd-host \
                    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN uhd_images_downloader

CMD /usr/bin/python3
