FROM ubuntu:20.04


RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive \
                   apt-get install -qy --no-install-recommends \
                   python3 python3-pip \
                   python3-dev python3-uhd \
                    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD /usr/bin/python3
