single_frequency_time_domain_iq:
  name: test_acquire_iq_750MHz_10s
  frequency: 750e6
  gain: 40
  sample_rate: 15.36e6
  duration_ms: 10000
  nskip: 15.36e4
  classification: UNCLASSIFIED
  calibration_adjust: False
