single_frequency_time_domain_iq:
  name: acquire_iq_700MHz_T-Mobile_UL
  frequency: 700.5e6
  gain: 40
  sample_rate: 15.36e6
  duration_ms: 1000
  nskip: 15.36e4
  classification: UNCLASSIFIED
  calibration_adjust: true
