single_frequency_fft:
  name: acquire_m4s_700MHz_ATT_DL
  frequency: 739e6
  gain: 40
  sample_rate: 15.36e6
  fft_size: 1024
  nffts: 300
  nskip: 15.36e4
  classification: UNCLASSIFIED
  calibration_adjust: true