stepped_frequency_time_domain_iq:
  name: survey_700MHz_band_20dB_80ms_iq
  frequency:
    - 700.5e6
    - 709e6
    - 731.5e6
    - 739e6
    - 751e6
    - 763e6
    - 772e6
    - 782e6
    - 793e6
    - 802e6
  gain: 20
  sample_rate: 15.36e6
  duration_ms: 80
  nskip: 15.36e4
  classification: UNCLASSIFIED
  calibration_adjust: True
